name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Search Engine Backend
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bedman3/comp4321-search-engine
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "search-engine-backend"
    - name: Build Search Engine Frontend
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bedman3/comp4321-search-engine
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: search-engine-frontend
        tags: "search-engine-frontend"
    - name: Build Search Engine Frontend For AWS
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bedman3/comp4321-search-engine
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: search-engine-frontend
        tags: "search-engine-frontend-aws"
        docerfile: DockerfileAWS

